config/routes.rb
Rails.application.routes.draw do
  get "/users/show", to: "users#show", as: "user"
  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :events do
    resources :attendances, only: [ :show, :create, :destroy ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_rich_text :description
  has_one_attached :featured_image

  # validations
  validates :date, presence: true
  validates :location, presence: true
  validates :title, presence: true

  # associations
  belongs_to :creator, class_name: "User"
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendances

  # scopes
  scope :past, -> { where("date < ?", Date.today) }
  scope :upcoming, -> { where("date >= ?", Date.today) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :verify_event_creator, only: %i[ edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    if user_signed_in?
      @attendance = current_user.attendances.find_by(attended_event_id: @event.id)
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    # @event = Event.new(event_params)
    @event= current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.expect(event: [ :title, :description, :date, :location, :featured_image ])
    end

    # verify event creator
    def verify_event_creator
      if @event.creator_id != current_user.id
        redirect_to event_path(@event), alert: "You are not authorized! Only creator can delete this event."
      end
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <%= image_tag event.featured_image if event.featured_image.attached? %>

  <p>
    <h3><%= event.title %></h3>
  </p>
  
  <p>
    <strong>Date:</strong>
    <%= event.date %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>Created by: </strong>
    <%= event.creator.username %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.label :featured_image, style: "display: block" %>
    <%= form.file_field :featured_image, accept: "image/*" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<% content_for :title, "Editing event" %>

<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Events" %>

<h1>Events</h1>

<% if user_signed_in? %>
  <p><%= link_to "New event", new_event_path %></p>
<% end %>

<h2>Past Events</h2>
<div id="events">
  <% if @events.past.present? %>
    <% @events.past.each do |event| %>
      <%= render event %>
      <p>
        <%= link_to "Show this event", event %>
      </p>
    <% end %>
  <% else %>
    <p>No past events</p>
  <% end%>
</div>

<h2>Upcoming Events</h2>
<div id="events">
  <% if @events.upcoming.present? %>
    <% @events.upcoming.each do |event| %>
      <%= render event %>
      <p>
        <%= link_to "Show this event", event %>
      </p>
    <% end %>
  <% else %>
    <p>No upcoming events</p>
  <% end%>
</div>

app/views/events/new.html.erb
<% content_for :title, "New event" %>

<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p><%= link_to "Back to events", events_path %></p>

<h1>Event Details</h1>

<p style="color: green"><%= notice %></p>

<div>
  <%= render @event %>
  <p>
    <strong>Description:</strong>
    <%= @event.description %>
  </p>
</div>

<div>
  <% if user_signed_in? %>
    <% if (@event.creator_id == current_user.id)%>
      <p><%= link_to "Edit this event", edit_event_path(@event) %></p>
      <p><%= button_to "Destroy this event", @event, method: :delete %></p>
    <% else %>
      <% if @attendance.present? %>
        <p><%= button_to "Cancel attendance", event_attendance_path(@event, @attendance), method: :delete %> </p>
      <% else %>
        <p><%= button_to "Attend this event", event_attendances_path(@event), method: :post %></p>
      <% end %>
    <% end %>
  <% end %>
</div>

<div>
  <h2>List of attendees for this event:</h2>
  <% if @event.attendances.present? %>
    <% @event.attendances.each do |attendance| %>
      <p><%= attendance.attendee.username %></p>
    <% end %>
  <% else %>
    <p>No attendees yet</p>
  <% end%>
</div>